site_name: Documentação hollow

nav:
  - Home page: index.md
  - Sobre:
    - Informações globais: about/about.md
    - Contribuir: about/contributing.md
  - Deploy e produção:
    - Como dar deploy no site: deployment/deploy.md
    - Manuntenção do site: deployment/maintenance.md
    - Servidor: deployment/server.md
  - Admin:
    - Para o admin: admin/admin.md
    - Como usar o site admin: admin/how-to-use.md
    - Papel do admin: admin/role.md
  - Banco de dados:
    - BDD: database/database.md
    - PostgreSQL: database/postgres.md
    - SQL: database/queries.md
  - Django:
    - O framework: django/django.md
    - Python: django/python.md
  - Desenvolvimento:
    - Ferramentas de desenvolvimento: development/tools.md
    - Setup do dev env: development/env.md
    - Workflow de dev: development/dev.md
    - Executar o server em local: development/run-project-locally.md
    - Como adicionar uma nova funcionalidade: development/adding-feature.md
    - Testes: development/testing.md
  - Heroku:
    - O Aplicativo Hollow: heroku/app.md
    - Dados: heroku/data.md
    - Heroku: heroku/heroku.md
    - Arquivos estáticos: heroku/static-files.md
  - Contato:
    - Nos contacte: contact/contact-us.md
  - MKDOCS: mkdocs.md

theme:
  name: material
  language: pt
  palette:
    primary: yellow
    accent: indigo
  font:
    text: Ubuntu
    code: Ubuntu Mono
  logo: 'img/favicon-hollow.png'
  favicon: 'img/favicon-hollow.png'

repo_name: coding55/hollow-docs
repo_url: https://github.com/coding55/hollow-docs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/coding55
    - icon: fontawesome/solid/users
      link: https://www.hollow.pt/

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true